"""api_token pub_key

Revision ID: bec4533cf379
Revises: 
Create Date: 2024-12-27 18:57:54.208555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec4533cf379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pubkey', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('api_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_token')
        batch_op.drop_column('pubkey')

    # ### end Alembic commands ###
